pipeline
{
	agent 
	{
		label
		{
					label 'built-in'
		
				//customWorkspace '/data/project'
		
		}
	}
	stages
		{
		stage('Install apache')
		{
			steps
			{
			      
					sh "yum install httpd -y"
			   
			}
			
			}
		
		
		stage('start-apache')
		{
			
			steps
			{
			    sh "rm -rf *"
			    
		    	sh "service httpd start"
			}
		}
		
		stage('deploy')
		{
			
			steps
			{
			    sh "cd /data/project"
			    
		    	sh "cp -r /data/project/index.html /var/www/html"
				sh "chmod -R 777 /var/www/html/index.html"
			}
		}
	}
	
}
